# Generated by Django 5.1.3 on 2024-11-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whole_city',
            old_name='cities',
            new_name='city_Names',
        ),
        migrations.AlterField(
            model_name='whole_city',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
